name: Unit tests
on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: [main]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5 
      - run: |
          python -m unittest unit_tests/test_my_utils.py  

  run_functional_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5 
      - run: |
          bash unit_tests/test_print_fires.sh

  run_style_checks:
    runs-on: ubuntu-latest

    steps:
      - run: pip install pycodestyle 
      - uses: actions/checkout@v5
      - run: pycodestyle $(git ls-files "*.py")
        shell: bash -l {0}